import type { LogisticsLocationType } from "./logistics-location-library";

export type ImportKind = "airports" | "ports" | "border_posts" | "generic";
export type ExternalRecord = Record<string, unknown>;
export type NormalizedImportLocation = { name: string; country: string; country_code: string; country_secondary: string | null; country_secondary_code: string | null; city: string | null; location_type: LogisticsLocationType; code: string | null; secondary_code: string | null; latitude: number | null; longitude: number | null; address: string | null; notes: string | null; source: string; source_reference: string | null; verified: boolean };
export type PreviewRecord = { index: number; status: "new" | "duplicate" | "invalid" | "review"; location: NormalizedImportLocation | null; issues: string[] };

const COUNTRY_ALIASES: Record<string, [string, string]> = { namibia: ["Namibia", "NA"], "south africa": ["South Africa", "ZA"], angola: ["Angola", "AO"], zambia: ["Zambia", "ZM"], botswana: ["Botswana", "BW"], zimbabwe: ["Zimbabwe", "ZW"], mozambique: ["Mozambique", "MZ"], nigeria: ["Nigeria", "NG"], ghana: ["Ghana", "GH"], kenya: ["Kenya", "KE"], uganda: ["Uganda", "UG"], tanzania: ["Tanzania", "TZ"], "democratic republic of the congo": ["DRC", "CD"], drc: ["DRC", "CD"], "united arab emirates": ["United Arab Emirates", "AE"], uae: ["United Arab Emirates", "AE"], china: ["China", "CN"] };
const aliases = { name: ["name", "airport_name", "port_name", "official_name", "facility_name"], country: ["country", "country_name", "country_a"], countryCode: ["country_code", "iso_country", "iso2", "iso_country_code", "country_a_code"], countrySecondary: ["country_secondary", "country_b"], countrySecondaryCode: ["country_secondary_code", "country_b_code"], city: ["city", "municipality", "region", "nearest_city"], primary: ["code", "primary_code", "iata", "iata_code", "unlocode", "un_locode", "locode", "port_code", "gps_code"], secondary: ["secondary_code", "icao", "icao_code"], latitude: ["latitude", "lat"], longitude: ["longitude", "lon", "lng"], address: ["address"], reference: ["source_reference", "id", "ident"] };

function clean(value: unknown) { return value == null ? "" : String(value).trim(); }
function field(record: ExternalRecord, names: string[]) { const entries = Object.entries(record); for (const name of names) { const match = entries.find(([key]) => key.trim().toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "") === name); if (match && clean(match[1])) return clean(match[1]); } return ""; }
function coordinate(value: string, min: number, max: number) { if (!value) return null; const number = Number(value); return Number.isFinite(number) && number >= min && number <= max ? number : null; }
function country(record: ExternalRecord) { const raw = field(record, aliases.country); const rawCode = field(record, aliases.countryCode).toUpperCase(); const known = COUNTRY_ALIASES[raw.toLowerCase()]; return { name: known?.[0] ?? raw, code: /^[A-Z]{2}$/.test(rawCode) ? rawCode : known?.[1] ?? "" }; }
function typeFor(kind: ImportKind, record: ExternalRecord): LogisticsLocationType { if (kind === "airports") return "airport"; if (kind === "ports") return "seaport"; if (kind === "border_posts") return "border_post"; const raw = field(record, ["location_type", "type"]).toLowerCase().replaceAll(" ", "_"); const valid: LogisticsLocationType[] = ["airport", "seaport", "border_post", "warehouse", "distribution_centre", "customs_facility", "rail_terminal", "inland_container_depot", "cargo_terminal", "delivery_depot", "other"]; return valid.includes(raw as LogisticsLocationType) ? raw as LogisticsLocationType : "other"; }

export function normalizeImportRecord(record: ExternalRecord, kind: ImportKind, source: string, verified = false): NormalizedImportLocation {
  const place = country(record); const type = typeFor(kind, record);
  const secondaryCountryName = field(record, aliases.countrySecondary);
  const secondaryCountryCode = field(record, aliases.countrySecondaryCode).toUpperCase();
  return { name: field(record, aliases.name), country: place.name, country_code: place.code, country_secondary: secondaryCountryName || null, country_secondary_code: /^[A-Z]{2}$/.test(secondaryCountryCode) ? secondaryCountryCode : null, city: field(record, aliases.city) || null, location_type: type, code: field(record, aliases.primary).toUpperCase() || null, secondary_code: field(record, aliases.secondary).toUpperCase() || null, latitude: coordinate(field(record, aliases.latitude), -90, 90), longitude: coordinate(field(record, aliases.longitude), -180, 180), address: field(record, aliases.address) || null, notes: field(record, ["notes", "description"]) || null, source, source_reference: field(record, aliases.reference) || null, verified };
}
export function importAirports(records: ExternalRecord[], source = "airport_dataset", verified = false) { return records.map((record) => normalizeImportRecord(record, "airports", source, verified)); }
export function importPorts(records: ExternalRecord[], source = "port_dataset", verified = false) { return records.map((record) => normalizeImportRecord(record, "ports", source, verified)); }
export function importBorderPosts(records: ExternalRecord[], source = "border_dataset", verified = false) { return records.map((record) => normalizeImportRecord(record, "border_posts", source, verified)); }

export function parseCsv(text: string): ExternalRecord[] { const rows: string[][] = []; let row: string[] = [], value = "", quoted = false; for (let i = 0; i < text.length; i += 1) { const char = text[i]; if (char === '"') { if (quoted && text[i + 1] === '"') { value += '"'; i += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { row.push(value); value = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[i + 1] === "\n") i += 1; row.push(value); if (row.some((cell) => cell.trim())) rows.push(row); row = []; value = ""; } else value += char; } row.push(value); if (row.some((cell) => cell.trim())) rows.push(row); const [headers, ...data] = rows; if (!headers) return []; return data.map((cells) => Object.fromEntries(headers.map((header, index) => [header.trim().toLowerCase(), cells[index]?.trim() ?? ""]))); }
export function parseImportFile(text: string, filename: string): ExternalRecord[] { if (filename.toLowerCase().endsWith(".json")) { const parsed: unknown = JSON.parse(text); if (!Array.isArray(parsed)) throw new Error("JSON import must contain an array of records."); return parsed.filter((item): item is ExternalRecord => Boolean(item) && typeof item === "object" && !Array.isArray(item)); } return parseCsv(text); }

export function normalizeIdentityText(value: string | null | undefined) { return (value ?? "").toLowerCase().replace(/[^\p{L}\p{N}]+/gu, " ").trim().replace(/\s+/g, " "); }
export function normalizeSeaportName(value: string) { return normalizeIdentityText(value).replace(/^(port of|port)\s+/, "").replace(/\s+port$/, "").trim(); }
function importIdentity(location: NormalizedImportLocation) {
  if (location.code) return `${location.location_type}|${location.country_code}|code:${location.code.toLowerCase()}`;
  const name = location.location_type === "seaport" ? normalizeSeaportName(location.name) : location.name.toLowerCase();
  const city = location.location_type === "seaport" ? normalizeIdentityText(location.city) : location.city?.toLowerCase() ?? "";
  return `${location.location_type}|${location.country_code}|${name}|${city}`;
}

export function buildImportPreview(locations: NormalizedImportLocation[]): PreviewRecord[] { const seen = new Set<string>(); return locations.map((location, index) => { const issues: string[] = []; if (!location.name) issues.push("Missing official name"); if (!location.country) issues.push("Missing country"); if (!/^[A-Z]{2}$/.test(location.country_code)) issues.push("Missing or invalid ISO country code"); const identity = importIdentity(location); if (seen.has(identity)) return { index, status: "duplicate", location, issues: ["Duplicate within uploaded file"] }; seen.add(identity); if (issues.length) return { index, status: "invalid", location, issues }; const review: string[] = []; if (location.location_type === "airport" && !location.code) review.push("No verified primary code supplied"); if (!location.city) review.push("City or region not supplied"); if (!location.verified) review.push("Dataset record is not marked verified"); return { index, status: review.length ? "review" : "new", location, issues: review }; }); }
