"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import ShipmentDocumentsManager from "../components/ShipmentDocumentsManager";
import { automateShipmentOperations } from "../lib/operations-automation";
import { convertWeightDisplay, PACKAGE_HELPERS, PACKAGE_TYPE_OPTIONS, WEIGHT_UNITS, weightHelper, type WeightUnit } from "../lib/package-fields";
import type { RouteJourney } from "../lib/route-intelligence";
import { loadSavedRoute, type SavedRouteStop } from "../lib/saved-routes";
import { loadShipmentRouteSnapshot } from "../lib/shipment-route-snapshots";

export const TRANSPORT_OPTIONS = ["Air", "Sea", "Road", "Multimodal", "Rail"] as const;

export type ShipmentEditorRecord = {
  id: number; tracking_number: string; client_name: string; client_email: string | null;
  client_company_name: string | null; client_phone: string | null; client_address: string | null; client_receive_updates: boolean;
  origin_country: string; destination_country: string; current_location: string | null;
  vessel_name: string | null;
  courier_name: string | null; item_description: string | null; estimated_delivery: string | null;
  weight_kg: number | null; package_count: number | null; package_type: string | null;
  dimensions: string | null; container_number: string | null; seal_number: string | null;
  declared_value: number | null; transport_mode: string | null; receiver_name: string | null;
  receiver_phone: string | null; receiver_email: string | null; receiver_address: string | null;
  receiver_company_name: string | null; receiver_receive_updates: boolean;
  shipment_status: string | null; created_at: string; route_template_id: string | null; current_route_checkpoint_id: string | null;
};

export type ShipmentEditForm = {
  tracking_number: string; client_name: string; client_email: string; origin_country: string;
  client_company_name: string; client_phone: string; client_address: string; client_receive_updates: string;
  destination_country: string; current_location: string; courier_name: string; item_description: string;
  estimated_delivery: string; transport_mode: string; receiver_name: string; receiver_phone: string;
  vessel_name: string;
  receiver_email: string; receiver_address: string; shipment_status: string; update_note: string;
  receiver_company_name: string; receiver_receive_updates: string;
  weight_kg: string; weight_unit: WeightUnit; package_count: string; package_type: string;
  dimensions: string; container_number: string; seal_number: string; declared_value: string; route_template_id: string; current_route_checkpoint_id: string;
};

type Props = {
  shipment: ShipmentEditorRecord; form: ShipmentEditForm; statusOptions: readonly string[];
  errors: Record<string, string>; saving: boolean; success: string;
  onChange: (field: keyof ShipmentEditForm, value: string) => void;
  onSubmit: (event: FormEvent<HTMLFormElement>, authoritativeCurrentLocation?: string) => void; onClose: () => void;
};

type AssignedRouteView = {
  name: string;
  source: "snapshot" | "template";
  stops: SavedRouteStop[];
  journey: RouteJourney | null;
};

export function ShipmentEditor({ shipment, form, statusOptions, errors, saving, success, onChange, onSubmit, onClose }: Props) {
  const [assignedRoute, setAssignedRoute] = useState<AssignedRouteView | null>(null);
  const [routeLoading, setRouteLoading] = useState(true);
  const [routeError, setRouteError] = useState("");
  const automation = useMemo(() => automateShipmentOperations({ shipmentStatus: form.shipment_status, exactCheckpointId: form.current_route_checkpoint_id || null, transportMode: form.transport_mode, origin: form.origin_country || shipment.origin_country, destination: form.destination_country || shipment.destination_country, journey: assignedRoute?.journey ?? null, receiverAddress: form.receiver_address, estimatedDelivery: form.estimated_delivery, operationalNote: form.update_note }), [assignedRoute?.journey, form, shipment.destination_country, shipment.origin_country]);
  const selectedCheckpoint = assignedRoute?.source === "snapshot" ? assignedRoute.journey?.checkpoints.find((checkpoint) => checkpoint.id === form.current_route_checkpoint_id) : undefined;
  const checkpointJourney = assignedRoute?.source === "snapshot" ? assignedRoute.journey : null;
  const checkpointOptionsKey = checkpointJourney?.checkpoints.map((checkpoint) => checkpoint.id).join("|") || "legacy-checkpoints";
  const resolvedCurrentLocation = selectedCheckpoint?.kind === "delivered" ? automation.currentLocation : selectedCheckpoint?.location.name ?? form.current_location;
  const availableStatusOptions = automation.statusOptions.length ? [...new Set([form.shipment_status, ...automation.statusOptions])] : [...statusOptions];
  const changeWeightUnit = (unit: WeightUnit) => {
    onChange("weight_kg", convertWeightDisplay(form.weight_kg, form.weight_unit, unit));
    onChange("weight_unit", unit);
  };

  useEffect(() => { const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape" && !saving) onClose(); }; window.addEventListener("keydown", closeOnEscape); return () => window.removeEventListener("keydown", closeOnEscape); }, [onClose, saving]);

  useEffect(() => {
    let active = true;
    void (async () => {
      const snapshotResult = await loadShipmentRouteSnapshot(shipment.id);
      if (!active) return;
      if (snapshotResult.snapshot) {
        setAssignedRoute({ name: snapshotResult.snapshot.template_name, source: "snapshot", stops: snapshotResult.stops, journey: snapshotResult.journey });
        setRouteError("");
        setRouteLoading(false);
        return;
      }
      if (shipment.route_template_id) {
        const templateResult = await loadSavedRoute(shipment.route_template_id);
        if (!active) return;
        if (templateResult.template) setAssignedRoute({ name: templateResult.template.name, source: "template", stops: templateResult.stops, journey: templateResult.journey });
        else setAssignedRoute(null);
        setRouteError((snapshotResult.error ?? templateResult.error)?.message ?? "");
      } else {
        setAssignedRoute(null);
        setRouteError(snapshotResult.error?.message ?? "");
      }
      setRouteLoading(false);
    })();
    return () => { active = false; };
  }, [shipment.id, shipment.route_template_id]);

  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-3 backdrop-blur-sm sm:p-5" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <div role="dialog" aria-modal="true" aria-labelledby="shipment-editor-title" className="mx-auto w-full max-w-6xl overflow-hidden rounded-2xl border border-white/20 bg-[#f4f7fb] shadow-2xl">
      <header className="sticky top-0 z-20 flex items-start justify-between gap-5 border-b border-blue-950/10 bg-[#071a33] px-5 py-3.5 text-white sm:px-6"><div><p className="text-[0.6rem] font-black uppercase tracking-[0.16em] text-yellow-300">Shipment management</p><h2 id="shipment-editor-title" className="mt-0.5 text-xl font-black">Edit Shipment</h2><p className="mt-0.5 break-all text-xs font-bold text-blue-200">{shipment.tracking_number}</p></div><button type="button" onClick={onClose} aria-label="Close shipment editor" className="grid h-9 w-9 place-items-center rounded-xl border border-white/15 bg-white/5 text-xl hover:bg-white/10">×</button></header>

      <form onSubmit={(event) => onSubmit(event, resolvedCurrentLocation)} noValidate>
        <div className="grid gap-3 p-4 sm:p-5">
          {success && <p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm font-bold text-emerald-800">{success}</p>}
          {errors.form && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-bold text-red-700">{errors.form}</p>}
          <section className="rounded-2xl border border-blue-200 bg-white p-4 shadow-sm" aria-labelledby="quick-update-title"><div className="mb-3 flex items-center justify-between gap-3"><div><p className="text-[0.58rem] font-black uppercase tracking-[0.16em] text-blue-600">Daily operations</p><h3 id="quick-update-title" className="text-lg font-black text-[#071a33]">Quick Update</h3></div><button type="submit" disabled={saving} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-black text-white shadow-md shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-50">{saving ? "Saving…" : "Save Update"}</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><CheckpointStatusField key={checkpointOptionsKey} value={form.shipment_status} checkpointId={form.current_route_checkpoint_id} journey={checkpointJourney} fallbackOptions={availableStatusOptions} error={errors.shipment_status} onChange={(status, checkpointId, checkpointLocation) => { onChange("shipment_status", status); onChange("current_route_checkpoint_id", checkpointId); if (checkpointLocation) onChange("current_location", checkpointLocation); }}/><InputField label="Current Location" value={resolvedCurrentLocation} error={errors.current_location} onChange={(value) => onChange("current_location", value)}/><InputField label="Estimated Delivery" type="date" value={form.estimated_delivery} error={errors.estimated_delivery} onChange={(value) => onChange("estimated_delivery", value)}/><div className="sm:col-span-2 lg:col-span-1"><TextAreaField label="Update Note" value={form.update_note} onChange={(value) => onChange("update_note", value)} rows={1} placeholder="Optional when status changes" error={errors.update_note}/></div></div></section>

          <div className="grid min-w-0 gap-3">
            <EditorSection number="01" title="Shipment"><ReadOnlyField label="Tracking Number" value={form.tracking_number}/><SelectField label="Transport Mode" value={form.transport_mode} options={TRANSPORT_OPTIONS} error={errors.transport_mode} onChange={(value) => onChange("transport_mode", value)} required/><InputField label="Courier" value={form.courier_name} onChange={(value) => onChange("courier_name", value)}/></EditorSection>
            <EditorSection number="02" title="Sender / Supplier"><InputField key="sender-name" name="sender_name" autoComplete="name" label="Sender / Supplier Name" value={form.client_name} error={errors.client_name} onChange={(value) => onChange("client_name", value)} required/><InputField key="sender-company" name="sender_company_name" autoComplete="organization" label="Company Name" value={form.client_company_name} onChange={(value) => onChange("client_company_name", value)}/><InputField key="sender-phone" name="sender_phone" autoComplete="tel" label="Phone Number" helper="International format, for example +264 81 123 4567." type="tel" placeholder="+264 81 123 4567" value={form.client_phone} error={errors.client_phone} onChange={(value) => onChange("client_phone", value)}/><InputField key="sender-email" name="sender_email" autoComplete="email" label="Email Address" type="email" value={form.client_email} error={errors.client_email} onChange={(value) => onChange("client_email", value)}/><div className="sm:col-span-2"><TextAreaField label="Pickup / Origin Address" value={form.client_address} onChange={(value) => onChange("client_address", value)} rows={2}/></div><ToggleField label="Receive Shipment Updates" checked={form.client_receive_updates === "true"} onChange={(checked) => onChange("client_receive_updates", String(checked))}/></EditorSection>
            <EditorSection number="03" title="Receiver / Client"><InputField key="receiver-name" name="receiver_name" autoComplete="name" label="Receiver / Client Name" value={form.receiver_name} error={errors.receiver_name} onChange={(value) => onChange("receiver_name", value)} required/><InputField key="receiver-company" name="receiver_company_name" autoComplete="organization" label="Company Name" value={form.receiver_company_name} onChange={(value) => onChange("receiver_company_name", value)}/><InputField key="receiver-phone" name="receiver_phone" autoComplete="tel" label="Phone Number" helper="International format, for example +264 81 123 4567." type="tel" placeholder="+264 81 123 4567" value={form.receiver_phone} error={errors.receiver_phone} onChange={(value) => onChange("receiver_phone", value)}/><InputField key="receiver-email" name="receiver_email" autoComplete="email" label="Email Address" type="email" value={form.receiver_email} error={errors.receiver_email} onChange={(value) => onChange("receiver_email", value)}/><div className="sm:col-span-2"><TextAreaField label="Delivery Address" value={form.receiver_address} onChange={(value) => onChange("receiver_address", value)} rows={2}/></div><ToggleField label="Receive Shipment Updates" checked={form.receiver_receive_updates === "true"} onChange={(checked) => onChange("receiver_receive_updates", String(checked))}/></EditorSection>
            <EditorSection number="04" title="Package"><div className="sm:col-span-2"><TextAreaField label="Description" helper={PACKAGE_HELPERS.itemDescription} value={form.item_description} onChange={(value) => onChange("item_description", value)} rows={2}/></div><PackageTypeField value={form.package_type} onChange={(value) => onChange("package_type", value)}/><InputField label="Quantity / Package Count" helper={PACKAGE_HELPERS.packageQuantity} type="number" min="1" step="1" value={form.package_count} error={errors.package_count} onChange={(value) => onChange("package_count", value)}/><WeightField value={form.weight_kg} unit={form.weight_unit} error={errors.weight_kg} onChange={(value) => onChange("weight_kg", value)} onUnitChange={changeWeightUnit}/><InputField label="Dimensions" placeholder="120 × 80 × 100 cm" value={form.dimensions} onChange={(value) => onChange("dimensions", value)}/><InputField label="Container Number" placeholder="MSCU1234567" value={form.container_number} onChange={(value) => onChange("container_number", value)}/><InputField label="Seal Number" placeholder="ABC123456" value={form.seal_number} onChange={(value) => onChange("seal_number", value)}/><InputField label="Declared / Insured Value" type="number" min="0" step="0.01" value={form.declared_value} error={errors.declared_value} onChange={(value) => onChange("declared_value", value)}/></EditorSection>
            <EditorSection number="05" title="Route / Delivery"><InputField label="Origin" value={form.origin_country} error={errors.origin_country} onChange={(value) => onChange("origin_country", value)} required/><InputField label="Destination" value={form.destination_country} error={errors.destination_country} onChange={(value) => onChange("destination_country", value)} required/>{form.transport_mode === "Sea" && <InputField label="Vessel Name" placeholder="Enter vessel name" value={form.vessel_name} onChange={(value) => onChange("vessel_name", value)}/>}<div className="sm:col-span-2"><p className="text-[0.68rem] leading-4 text-slate-500">These country fields support legacy shipment data. They do not alter the authoritative assigned route shown below.</p></div><div className="sm:col-span-2"><AssignedRoutePanel route={assignedRoute} loading={routeLoading} error={routeError}/></div><ReadOnlyField label="Next Checkpoint" value={automation.nextCheckpoint} derived/><ReadOnlyField label="Next Location" value={automation.nextLocation} derived/></EditorSection>
            <EditorSection number="06" title="Documents"><div className="sm:col-span-2"><ShipmentDocumentsManager shipmentId={shipment.id} transportMode={form.transport_mode} cargoDescription={form.item_description}/></div></EditorSection>
          </div>
        </div>

        <footer className="sticky bottom-0 z-20 flex items-center justify-between gap-3 border-t border-slate-200 bg-white/95 px-4 py-3 backdrop-blur sm:px-5"><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700">Cancel</button><button type="submit" disabled={saving} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-black text-white disabled:opacity-50">{saving ? "Saving…" : "Save All Changes"}</button></footer>
      </form>
    </div>
  </div>;
}

function EditorSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { const [open, setOpen] = useState(false); const panelId = `shipment-editor-section-${number}`; return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-controls={panelId} className="flex w-full items-center gap-2 bg-slate-50/80 px-3.5 py-2.5 text-left hover:bg-slate-100"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-600 text-[0.62rem] font-black text-white">{number}</span><h3 className="flex-1 text-sm font-black text-[#071a33]">{title}</h3><span aria-hidden="true" className={`text-sm font-black text-slate-400 transition-transform ${open ? "rotate-180" : ""}`}>⌄</span></button>{open && <div id={panelId} className="grid gap-3 border-t border-slate-100 p-3.5 sm:grid-cols-2">{children}</div>}</section>; }
function labelClass() { return "mb-1.5 block text-[0.62rem] font-black uppercase tracking-[0.1em] text-slate-500"; }
function inputClass(error?: string, emphasis = false) { return `w-full rounded-xl border bg-white px-3 py-2.5 text-sm font-semibold text-slate-900 outline-none focus:ring-4 ${error ? "border-red-400 focus:ring-red-100" : emphasis ? "border-blue-500 ring-4 ring-blue-50 focus:ring-blue-100" : "border-slate-200 focus:border-blue-500 focus:ring-blue-100"}`; }
function InputField({ label, helper, value, onChange, error, required, type = "text", placeholder, min, step, name, autoComplete }: { label: string; helper?: string; value: string; onChange: (value: string) => void; error?: string; required?: boolean; type?: string; placeholder?: string; min?: string; step?: string; name?: string; autoComplete?: string }) { return <label><span className={labelClass()}>{label}{required && <span className="text-red-500"> *</span>}</span><input name={name} autoComplete={autoComplete} type={type} value={value} min={min} step={step} placeholder={placeholder} required={required} aria-invalid={Boolean(error)} onChange={(event) => onChange(event.target.value)} className={inputClass(error)}/>{helper && <span className="mt-1 block text-[0.68rem] leading-4 text-slate-500">{helper}</span>}{error && <span className="mt-1 block text-xs font-semibold text-red-600">{error}</span>}</label>; }
function SelectField({ label, value, options, onChange, error, required, emphasis }: { label: string; value: string; options: readonly string[]; onChange: (value: string) => void; error?: string; required?: boolean; emphasis?: boolean }) { return <label><span className={labelClass()}>{label}{required && <span className="text-red-500"> *</span>}</span><select value={value} required={required} aria-invalid={Boolean(error)} onChange={(event) => onChange(event.target.value)} className={inputClass(error, emphasis)}>{options.map((option) => <option key={option}>{option}</option>)}</select>{error && <span className="mt-1 block text-xs font-semibold text-red-600">{error}</span>}</label>; }
function CheckpointStatusField({ value, checkpointId, journey, fallbackOptions, error, onChange }: { value: string; checkpointId: string; journey: RouteJourney | null; fallbackOptions: readonly string[]; error?: string; onChange: (status: string, checkpointId: string, checkpointLocation?: string) => void }) { const checkpoints = journey?.checkpoints ?? []; const selectedCheckpoint = checkpoints.find((checkpoint) => checkpoint.id === checkpointId); const fallback = [...new Set(fallbackOptions.filter((option) => !checkpoints.some((checkpoint) => checkpoint.label === option)))]; const selectedValue = selectedCheckpoint ? `checkpoint:${selectedCheckpoint.id}` : `status:${value}`; return <label><span className={labelClass()}>Shipment Status<span className="text-red-500"> *</span></span><select value={selectedValue} required aria-invalid={Boolean(error)} onChange={(event) => { const selected = event.target.value; if (selected.startsWith("checkpoint:")) { const checkpoint = checkpoints.find((item) => item.id === selected.slice("checkpoint:".length)); if (checkpoint) onChange(checkpoint.label, checkpoint.id, checkpoint.location.name); } else onChange(selected.slice("status:".length), checkpointId); }} className={inputClass(error, true)}>{!selectedCheckpoint && <option value={`status:${value}`}>{value}</option>}{checkpoints.map((checkpoint) => <option key={checkpoint.id} value={`checkpoint:${checkpoint.id}`}>{checkpoint.label} — {checkpoint.location.name}</option>)}{fallback.map((option) => <option key={option} value={`status:${option}`}>{option}</option>)}</select>{error && <span className="mt-1 block text-xs font-semibold text-red-600">{error}</span>}</label>; }
function TextAreaField({ label, helper, value, onChange, rows, placeholder, error }: { label: string; helper?: string; value: string; onChange: (value: string) => void; rows: number; placeholder?: string; error?: string }) { return <label><span className={labelClass()}>{label}</span><textarea rows={rows} value={value} placeholder={placeholder} aria-invalid={Boolean(error)} onChange={(event) => onChange(event.target.value)} className={inputClass(error)}/>{helper && <span className="mt-1 block text-[0.68rem] leading-4 text-slate-500">{helper}</span>}{error && <span className="mt-1 block text-xs font-semibold text-red-600">{error}</span>}</label>; }
function PackageTypeField({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label><span className={labelClass()}>Package Type</span><input list="edit-package-types" value={value} onChange={(event) => onChange(event.target.value)} placeholder="Select or enter a type" className={inputClass()}/><datalist id="edit-package-types">{PACKAGE_TYPE_OPTIONS.map((option) => <option key={option} value={option}/>)}</datalist><span className="mt-1 block text-[0.68rem] leading-4 text-slate-500">{PACKAGE_HELPERS.packageType}</span></label>; }
function WeightField({ value, unit, error, onChange, onUnitChange }: { value: string; unit: WeightUnit; error?: string; onChange: (value: string) => void; onUnitChange: (unit: WeightUnit) => void }) { return <label><span className={labelClass()}>Total Weight</span><div className="flex"><input type="number" min="0" step="any" value={value} aria-invalid={Boolean(error)} onChange={(event) => onChange(event.target.value)} className={`${inputClass(error)} rounded-r-none`}/><select aria-label="Weight unit" value={unit} onChange={(event) => onUnitChange(event.target.value as WeightUnit)} className="w-20 rounded-r-xl border border-l-0 border-slate-200 bg-slate-50 px-2 text-xs font-black text-slate-700 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100">{WEIGHT_UNITS.map((option) => <option key={option}>{option}</option>)}</select></div><span className="mt-1 block text-[0.68rem] leading-4 text-slate-500">{weightHelper(unit)}</span>{error && <span className="mt-1 block text-xs font-semibold text-red-600">{error}</span>}</label>; }
function ToggleField({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex min-h-11 items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50/60 px-3 py-2.5"><span><span className="block text-xs font-black text-slate-700">{label}</span><span className="mt-0.5 block text-[0.65rem] text-slate-500">Admin-controlled preference</span></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-blue-600"/></label>; }
function AssignedRoutePanel({ route, loading, error }: { route: AssignedRouteView | null; loading: boolean; error: string }) { return <section className="rounded-xl border border-blue-100 bg-blue-50/40 p-3" aria-labelledby="assigned-route-title"><div className="flex flex-wrap items-start justify-between gap-2"><div><span className={labelClass()}>Assigned Route</span><h4 id="assigned-route-title" className="text-sm font-black text-[#071a33]">{route?.name || "No saved route assigned"}</h4>{route && <p className="mt-0.5 text-[0.65rem] font-semibold text-blue-700">{route.source === "snapshot" ? "Immutable shipment snapshot" : "Saved Route Library fallback"}</p>}</div><Link href="/admin/routes" className="rounded-lg border border-blue-200 bg-white px-2.5 py-1.5 text-[0.65rem] font-black text-blue-700 hover:bg-blue-50">Manage Route Library</Link></div>{loading ? <p className="mt-3 text-xs font-semibold text-slate-500">Loading assigned route…</p> : route?.stops.length ? <ol className="mt-3 grid gap-1.5" aria-label="Assigned route stops">{route.stops.map((stop, index) => <li key={stop.id} className="relative grid grid-cols-[1.5rem_minmax(0,1fr)] gap-2 rounded-lg border border-slate-100 bg-white px-2.5 py-2 shadow-sm">{index < route.stops.length - 1 && <span aria-hidden="true" className="absolute bottom-[-0.55rem] left-[1.2rem] top-8 w-px bg-blue-200"/>}<span className="relative z-10 grid h-6 w-6 place-items-center rounded-full bg-blue-600 text-[0.6rem] font-black text-white">{index + 1}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-1.5"><p className="break-words text-xs font-black text-slate-800">{stop.name}{stop.code && <span className="ml-1 text-blue-700">({stop.code})</span>}</p><span className="rounded-full bg-slate-100 px-1.5 py-0.5 text-[0.55rem] font-bold uppercase tracking-wide text-slate-500">{formatStopType(stop.stop_type)}</span>{stop.onward_transport && <span className="rounded-full bg-blue-50 px-1.5 py-0.5 text-[0.55rem] font-bold text-blue-700">Next: {stop.onward_transport}</span>}</div><p className="mt-0.5 text-[0.68rem] font-medium text-slate-500">{[stop.city, stop.country].filter(Boolean).join(", ")}</p></div></li>)}</ol> : <p className="mt-3 rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-500">This legacy shipment has no saved route snapshot. Origin and destination country fields remain the fallback.</p>}{error && <p className="mt-2 text-[0.68rem] font-semibold text-amber-700">Assigned route details could not be fully loaded: {error}</p>}<p className="mt-2 text-[0.65rem] leading-4 text-slate-500">Managing the Route Library does not replace this shipment&apos;s immutable snapshot.</p></section>; }
function formatStopType(value: string) { return value.replaceAll("_", " "); }
function ReadOnlyField({ label, value, derived }: { label: string; value: string; derived?: boolean }) { return <div><span className={labelClass()}>{label}{derived && <span className="ml-2 rounded-full bg-blue-50 px-2 py-0.5 text-[0.55rem] text-blue-700">Derived</span>}</span><div className="min-h-10 rounded-xl border border-slate-200 bg-slate-100 px-3 py-2.5 text-sm font-semibold text-slate-700">{value}</div></div>; }
