"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { categoryTone, NOTIFICATION_CATEGORIES, NOTIFICATION_CHANNELS, NOTIFICATION_TYPES, type NotificationChannel, type SmartNotification } from "../lib/notification-types";
import { supabase } from "../lib/supabase";

type Props = { shipment: { id: number; tracking_number: string; client_name: string; client_email: string | null; receiver_name: string | null; receiver_email: string | null; receiver_phone: string | null; shipment_status: string | null; current_location: string | null } };
type Template = { id: string; name: string; notification_type: string; category: string; channel: NotificationChannel; subject: string; message: string };
const scheduleOptions = [{ label: "15 minutes", minutes: 15 }, { label: "30 minutes", minutes: 30 }, { label: "1 hour", minutes: 60 }, { label: "3 hours", minutes: 180 }, { label: "Tomorrow 08:00", minutes: -1 }, { label: "Custom", minutes: -2 }];

export default function ShipmentNotificationManager({ shipment }: Props) {
  const recipient = shipment.receiver_email || shipment.client_email || "";
  const [rows, setRows] = useState<SmartNotification[]>([]); const [templates, setTemplates] = useState<Template[]>([]);
  const [type, setType] = useState("In Transit"); const [category, setCategory] = useState("Information"); const [channel, setChannel] = useState<NotificationChannel>("email");
  const [subject, setSubject] = useState(`Shipment update - ${shipment.tracking_number}`); const [message, setMessage] = useState(`Hello ${shipment.receiver_name || shipment.client_name}, your shipment is currently ${shipment.shipment_status || "being processed"}. Current location: ${shipment.current_location || "Not available"}.`);
  const [scheduleBase] = useState(() => new Date());
  const [mode, setMode] = useState<"Send Now" | "Schedule" | "Save Only">("Send Now"); const [scheduleChoice, setScheduleChoice] = useState("15 minutes"); const [customDate, setCustomDate] = useState("");
  const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState("All"); const [editing, setEditing] = useState<string | null>(null); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [settingsOpen, setSettingsOpen] = useState(false);

  const refresh = useCallback(async () => {
    const [{ data, error: loadError }, { data: templateRows }] = await Promise.all([
      supabase.from("notification_history").select("*").eq("shipment_id", shipment.id).order("created_at", { ascending: false }).limit(100),
      supabase.from("notification_templates").select("id,name,notification_type,category,channel,subject,message").eq("active", true).order("name"),
    ]);
    if (loadError) setError(loadError.message); else setRows((data ?? []) as SmartNotification[]);
    setTemplates((templateRows ?? []) as Template[]);
  }, [shipment.id]);
  useEffect(() => { const timer = window.setTimeout(() => void refresh(), 0); return () => window.clearTimeout(timer); }, [refresh]);

  const filtered = useMemo(() => rows.filter((row) => (statusFilter === "All" || row.status === statusFilter) && `${row.notification_type} ${row.subject} ${row.message}`.toLowerCase().includes(search.toLowerCase())), [rows, search, statusFilter]);
  function scheduledAt() { const choice = scheduleOptions.find((item) => item.label === scheduleChoice); if (!choice || choice.minutes === -2) return customDate ? new Date(customDate).toISOString() : null; if (choice.minutes === -1) { const next = new Date(scheduleBase); next.setDate(next.getDate() + 1); next.setHours(8, 0, 0, 0); return next.toISOString(); } return new Date(scheduleBase.getTime() + choice.minutes * 60_000).toISOString(); }
  function reset() { setEditing(null); setType("In Transit"); setCategory("Information"); setChannel("email"); setSubject(`Shipment update - ${shipment.tracking_number}`); setMessage(`Hello ${shipment.receiver_name || shipment.client_name}, there is a new update for your shipment.`); setNotice(""); setError(""); }
  function applyTemplate(template: Template) { setType(template.notification_type); setCategory(template.category); setChannel(template.channel); setSubject(template.subject.replaceAll("{{tracking_number}}", shipment.tracking_number)); setMessage(template.message.replaceAll("{{tracking_number}}", shipment.tracking_number).replaceAll("{{current_location}}", shipment.current_location || "Not available")); }
  function assist(action: string) { let next = message.trim().replace(/\s+/g, " "); if (!next) return; if (action === "Shorter") next = next.split(/(?<=[.!?])\s/).slice(0, 2).join(" "); else if (action === "Reassuring") next = `${next} Our operations team is monitoring your shipment and will share the next confirmed update.`; else if (action === "Friendly") next = next.replace(/^Hello[, ]*/i, `Hello ${shipment.receiver_name || shipment.client_name}, `); else if (action === "Formal") next = next.replace(/\bwe're\b/gi, "we are").replace(/\byour package\b/gi, "your shipment"); else next = next.charAt(0).toUpperCase() + next.slice(1); setMessage(next); setNotice(`AI Assist suggestion applied: ${action}. Review before sending.`); }

  async function saveNotification() {
    setError(""); setNotice(""); if (!recipient && channel === "email") { setError("Add a customer or receiver email before sending."); return; } if (!subject.trim() || !message.trim()) { setError("Subject and message are required."); return; }
    const sendAt = mode === "Schedule" ? scheduledAt() : null; if (mode === "Schedule" && !sendAt) { setError("Choose a valid schedule time."); return; }
    setBusy("save"); const status = mode === "Save Only" ? "Draft" : mode === "Schedule" ? "Scheduled" : "Pending";
    const payload = { shipment_id: shipment.id, notification_type: type, event_type: type.toLowerCase().replaceAll(" ", "_"), category, channel, recipient: channel === "email" ? recipient : shipment.receiver_phone, subject: subject.trim(), message: message.trim(), status, delivery_mode: mode, scheduled_at: sendAt, source: "manual", customer_visible: true, updated_at: new Date().toISOString() };
    const result = editing ? await supabase.from("notification_history").update(payload).eq("id", editing).select("id").single() : await supabase.from("notification_history").insert(payload).select("id").single();
    if (result.error) setError(result.error.message); else { const id = result.data.id as string; if (mode === "Send Now") { const response = await fetch("/api/notifications/send", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ notificationId: id }) }); const body = await response.json() as { status?: string; error?: string }; setNotice(body.status === "Sent" ? "Notification sent successfully." : body.error || `Notification saved as ${body.status}.`); } else setNotice(mode === "Schedule" ? "Notification scheduled." : "Draft saved without sending."); reset(); await refresh(); }
    setBusy("");
  }
  async function act(row: SmartNotification, action: "retry" | "cancel" | "delete" | "duplicate") { if (action === "retry" && !window.confirm("Resend this notification now?")) return; setBusy(row.id); setError(""); if (action === "retry") await fetch("/api/notifications/send", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ retryId: row.id }) }); else if (action === "cancel") await supabase.from("notification_history").update({ status: "Cancelled", cancelled_at: new Date().toISOString() }).eq("id", row.id); else if (action === "delete") await supabase.from("notification_history").delete().eq("id", row.id).in("status", ["Draft", "Pending", "Scheduled", "Cancelled"]); else { setEditing(null); setType(row.notification_type); setCategory(row.category); setChannel(row.channel); setSubject(`${row.subject || "Shipment update"} (copy)`); setMessage(row.message); window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }); } await refresh(); setBusy(""); }
  function edit(row: SmartNotification) { setEditing(row.id); setType(row.notification_type); setCategory(row.category); setChannel(row.channel); setSubject(row.subject || ""); setMessage(row.message); setMode(row.delivery_mode); }

  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 bg-slate-50/80 px-4 py-3"><div><p className="text-[0.6rem] font-black uppercase tracking-[0.16em] text-blue-600">Smart automation</p><h3 className="font-black text-[#071a33]">Shipment Notification Center</h3><p className="text-xs text-slate-500">Compose, schedule, preview, and audit every customer notification.</p></div><button type="button" onClick={() => setSettingsOpen((value) => !value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-black">Automation Settings</button></header>
    {settingsOpen && <AutomationSettings/>}<div className="grid gap-4 p-4 xl:grid-cols-[.9fr_1.1fr]"><div className="grid content-start gap-3 rounded-xl border border-slate-200 bg-slate-50/60 p-3"><div className="grid gap-3 sm:grid-cols-2"><Select label="Notification Type" value={type} options={NOTIFICATION_TYPES} onChange={setType}/><Select label="Category" value={category} options={NOTIFICATION_CATEGORIES} onChange={setCategory}/><Select label="Channel" value={channel} options={NOTIFICATION_CHANNELS} onChange={(value) => setChannel(value as NotificationChannel)}/><Select label="Delivery" value={mode} options={["Send Now","Schedule","Save Only"]} onChange={(value) => setMode(value as typeof mode)}/></div>
      {mode === "Schedule" && <div className="grid gap-3 sm:grid-cols-2"><Select label="Schedule" value={scheduleChoice} options={scheduleOptions.map((item) => item.label)} onChange={setScheduleChoice}/>{scheduleChoice === "Custom" && <label><span className={labelClass}>Custom Date & Time</span><input type="datetime-local" value={customDate} onChange={(event) => setCustomDate(event.target.value)} className={inputClass}/></label>}</div>}
      <label><span className={labelClass}>Template</span><select className={inputClass} defaultValue="" onChange={(event) => { const template = templates.find((item) => item.id === event.target.value); if (template) applyTemplate(template); }}><option value="">Choose reusable template</option>{templates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span className={labelClass}>Subject</span><input value={subject} onChange={(event) => setSubject(event.target.value)} className={inputClass}/></label><label><span className={labelClass}>Message</span><textarea rows={5} value={message} onChange={(event) => setMessage(event.target.value)} className={inputClass}/></label>
      <div className="flex flex-wrap gap-1.5" aria-label="AI writing suggestions">{["Grammar","Professional","Friendly","Human","Shorter","Formal","Reassuring"].map((item) => <button key={item} type="button" onClick={() => assist(item)} className="rounded-lg bg-white px-2.5 py-1.5 text-[0.65rem] font-bold text-slate-600 ring-1 ring-slate-200">{item}</button>)}</div>
      <div className="rounded-xl border border-blue-200 bg-blue-50 p-3"><p className="text-[0.6rem] font-black uppercase text-blue-700">Delivery Preview</p><dl className="mt-2 grid gap-1 text-xs"><div><b>Recipient:</b> {recipient || "Not available"}</div><div><b>Channel:</b> {channel}</div><div><b>Estimated send:</b> {mode === "Send Now" ? "Immediately" : mode === "Save Only" ? "Not sent" : scheduledAt() ? new Date(scheduledAt()!).toLocaleString() : "Choose time"}</div></dl><p className="mt-2 font-black text-[#071a33]">{subject}</p><p className="mt-1 whitespace-pre-line text-xs leading-5 text-slate-600">{message}</p></div>
      {error && <p role="alert" className="rounded-lg bg-red-50 p-2 text-xs font-bold text-red-700">{error}</p>}{notice && <p role="status" className="rounded-lg bg-emerald-50 p-2 text-xs font-bold text-emerald-700">{notice}</p>}<div className="flex gap-2">{editing && <button type="button" onClick={reset} className="rounded-lg border px-3 py-2 text-xs font-bold">Cancel Edit</button>}<button type="button" disabled={busy === "save"} onClick={() => void saveNotification()} className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-black text-white disabled:opacity-50">{busy === "save" ? "Working…" : editing ? "Update Notification" : mode}</button></div></div>
      <div className="min-w-0"><div className="mb-2 flex flex-col gap-2 sm:flex-row"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search notifications" className={`${inputClass} h-10 flex-1`}/><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className={`${inputClass} h-10 sm:w-44`}>{["All","Draft","Scheduled","Pending","Sent","Delivered","Failed","Provider Not Configured","Cancelled"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="max-h-[42rem] overflow-y-auto rounded-xl border border-slate-200">{!filtered.length ? <p className="p-8 text-center text-xs text-slate-500">No notifications match this view.</p> : <ul className="divide-y divide-slate-100">{filtered.map((row) => <li key={row.id} className="p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="flex flex-wrap items-center gap-1.5"><span className={`rounded-full border px-2 py-0.5 text-[0.58rem] font-black ${categoryTone(row.category)}`}>{row.notification_type}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[0.58rem] font-black">{row.status}</span>{row.read_at && <span className="text-[0.6rem] font-bold text-emerald-700">Viewed</span>}</div><p className="mt-1 truncate text-xs font-black">{row.subject}</p><p className="mt-1 line-clamp-2 text-[0.68rem] leading-4 text-slate-600">{row.message}</p><p className="mt-1 text-[0.6rem] text-slate-400">{new Date(row.created_at).toLocaleString()} · {row.channel} · {row.source}{row.batch_event_count > 1 ? ` · ${row.batch_event_count} batched updates` : ""}</p>{row.error_message && <p className="mt-1 text-[0.62rem] text-red-600">{row.error_message}</p>}</div></div><div className="mt-2 flex flex-wrap gap-1">{["Draft","Pending","Scheduled"].includes(row.status) && <button onClick={() => edit(row)} className={actionClass}>Edit</button>}{["Failed","Provider Not Configured"].includes(row.status) && <button onClick={() => void act(row,"retry")} className={actionClass}>Resend</button>}{["Pending","Scheduled"].includes(row.status) && <button onClick={() => void act(row,"cancel")} className={actionClass}>Cancel</button>}<button onClick={() => void act(row,"duplicate")} className={actionClass}>Duplicate</button>{["Draft","Pending","Scheduled","Cancelled"].includes(row.status) && <button onClick={() => void act(row,"delete")} className={`${actionClass} text-red-700`}>Delete</button>}</div></li>)}</ul>}</div></div></div></section>;
}

function AutomationSettings() { const [settings, setSettings] = useState<{event_type:string;enabled:boolean}[]>([]); const [batch, setBatch] = useState(5); useEffect(() => { void Promise.all([supabase.from("notification_automation_settings").select("event_type,enabled").order("event_type"), supabase.from("notification_system_settings").select("batch_window_minutes").eq("id", true).single()]).then(([a,b]) => { setSettings((a.data ?? []) as typeof settings); if (b.data) setBatch(b.data.batch_window_minutes); }); }, []); async function toggle(item: {event_type:string;enabled:boolean}) { await supabase.from("notification_automation_settings").update({ enabled: !item.enabled, updated_at: new Date().toISOString() }).eq("event_type", item.event_type); setSettings((rows) => rows.map((row) => row.event_type === item.event_type ? {...row, enabled: !row.enabled} : row)); } return <div className="border-b border-slate-100 bg-blue-50/50 p-4"><div className="mb-3 flex items-end gap-2"><label><span className={labelClass}>Smart batch window (minutes)</span><input type="number" min="0" max="1440" value={batch} onChange={(e) => setBatch(Number(e.target.value))} className={`${inputClass} w-36`}/></label><button onClick={() => void supabase.from("notification_system_settings").update({ batch_window_minutes: batch, updated_at: new Date().toISOString() }).eq("id", true)} className="h-10 rounded-lg bg-[#071a33] px-3 text-xs font-black text-white">Save</button></div><div className="flex flex-wrap gap-1.5">{settings.map((item) => <button key={item.event_type} onClick={() => void toggle(item)} className={`rounded-full px-2.5 py-1 text-[0.62rem] font-black ${item.enabled ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-500"}`}>{item.event_type.replaceAll("_"," ")} · {item.enabled ? "On" : "Off"}</button>)}</div></div>; }
const labelClass = "mb-1 block text-[0.62rem] font-black uppercase tracking-wider text-slate-500"; const inputClass = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100"; const actionClass = "rounded-md bg-slate-100 px-2 py-1.5 text-[0.62rem] font-bold text-slate-600 hover:bg-slate-200 disabled:opacity-40";
function Select({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(value:string)=>void}) { return <label><span className={labelClass}>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className={inputClass}>{options.map((item) => <option key={item}>{item}</option>)}</select></label>; }
