import type { CommunicationType, ShipmentCommunication } from "../lib/shipment-communications";

export default function ShipmentCommunications({ communications }: { communications: ShipmentCommunication[] }) {
  return <section aria-labelledby="shipment-communications-title"><div className="mb-2.5"><p className="text-[0.58rem] font-extrabold uppercase tracking-[0.18em] text-blue-600">Customer updates</p><h2 id="shipment-communications-title" className="text-lg font-black tracking-tight text-slate-950">Communication</h2></div><div className="overflow-hidden rounded-[1.25rem] border border-slate-200/70 bg-white shadow-[0_15px_38px_-27px_rgba(15,23,42,.34)]">{!communications.length ? <p className="px-5 py-8 text-center text-sm font-semibold text-slate-500">No customer communications are available.</p> : <ol className="px-3 py-2 sm:px-4">{communications.map((item, index) => <li key={item.id} className="relative grid grid-cols-[2.25rem_minmax(0,1fr)] gap-2.5 rounded-xl px-1.5 py-2.5 sm:grid-cols-[2.5rem_minmax(0,1fr)] sm:gap-3 sm:px-2">{index < communications.length - 1 && <span aria-hidden="true" className="absolute bottom-[-0.65rem] left-[1.6rem] top-10 w-0.5 bg-slate-200 sm:left-[1.75rem]"/>}<span className={`relative z-10 grid h-9 w-9 place-items-center rounded-xl border shadow-sm sm:h-10 sm:w-10 ${tone(item.type).icon}`}><CommunicationIcon type={item.type}/></span><article className={`min-w-0 rounded-xl border-l-4 px-3 py-2.5 ${tone(item.type).card}`}><div className="flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between sm:gap-4"><div><p className={`text-[0.58rem] font-black uppercase tracking-[0.12em] ${tone(item.type).label}`}>{item.type}</p><h3 className="mt-0.5 text-sm font-black text-slate-900">{item.title}</h3></div><time dateTime={item.created_at} className="shrink-0 text-[0.66rem] font-bold text-slate-500">{relativeDate(item.created_at)}</time></div><p className="mt-1.5 text-xs leading-5 text-slate-700">{item.message}</p><p className="mt-1 text-[0.62rem] font-semibold text-slate-400">{absoluteDate(item.created_at)}</p></article></li>)}</ol>}</div></section>;
}

function tone(type: CommunicationType) { if (type === "Delay") return { icon: "border-orange-200 bg-orange-100 text-orange-700", card: "border-orange-400 bg-orange-50/60", label: "text-orange-700" }; if (type === "Warning") return { icon: "border-red-200 bg-red-100 text-red-700", card: "border-red-500 bg-red-50/60", label: "text-red-700" }; if (type === "Customs") return { icon: "border-purple-200 bg-purple-100 text-purple-700", card: "border-purple-500 bg-purple-50/60", label: "text-purple-700" }; if (type === "Delivery" || type === "Success" || type === "Arrival") return { icon: "border-emerald-200 bg-emerald-100 text-emerald-700", card: "border-emerald-500 bg-emerald-50/60", label: "text-emerald-700" }; return { icon: "border-blue-200 bg-blue-100 text-blue-700", card: "border-blue-500 bg-blue-50/60", label: "text-blue-700" }; }
function relativeDate(value: string) { const date = new Date(value); const days = Math.floor((Date.now() - date.getTime()) / 86_400_000); if (days <= 0) return "Today"; if (days === 1) return "Yesterday"; if (days < 7) return `${days} days ago`; return new Intl.DateTimeFormat("en", { day: "2-digit", month: "short" }).format(date); }
function absoluteDate(value: string) { const date = new Date(value); const formatted = Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(date); return `Balo Logistics · ${formatted}`; }
function CommunicationIcon({ type }: { type: CommunicationType }) { return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="h-4 w-4">{type === "Customs" ? <><path d="M4 9h16M6 9V7l6-4 6 4v2M7 9v8M12 9v8M17 9v8M4 17h16v3H4z"/></> : type === "Delivery" || type === "Arrival" ? <><path d="M3 7h11v10H3zM14 10h4l3 3v4h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></> : type === "Success" ? <path d="m5 12 4 4L19 6"/> : type === "Warning" || type === "Delay" ? <><circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/></> : <><path d="M4 5h16v12H8l-4 4Z"/><path d="M8 9h8M8 13h5"/></>}</svg>; }
