"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { categoryTone, type SmartNotification } from "../lib/notification-types";
import { supabase } from "../lib/supabase";

const FILTERS = ["All", "Unread", "Shipment Updates", "Documents", "Messages", "Delays", "Delivered"] as const;

export default function CustomerNotificationCenter({ onUnreadChange }: { onUnreadChange?: (count: number) => void }) {
  const [rows, setRows] = useState<SmartNotification[]>([]); const [filter, setFilter] = useState<(typeof FILTERS)[number]>("All"); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { const { data } = await supabase.from("notification_history").select("*").eq("customer_visible", true).in("status", ["Sent", "Delivered"]).order("created_at", { ascending: false }).range(0, 99); const next = (data ?? []) as SmartNotification[]; setRows(next); onUnreadChange?.(next.filter((item) => !item.read_at).length); setLoading(false); }, [onUnreadChange]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const unread = rows.filter((item) => !item.read_at).length;
  const filtered = useMemo(() => rows.filter((row) => filter === "All" || (filter === "Unread" && !row.read_at) || (filter === "Documents" && row.category === "Document") || (filter === "Messages" && row.source === "shipment_communications") || (filter === "Delays" && row.category === "Delay") || (filter === "Delivered" && ["Success", "Delivery"].includes(row.category)) || (filter === "Shipment Updates" && !["Document", "Delay", "Success", "Delivery"].includes(row.category))), [filter, rows]);
  async function read(id: string) { await supabase.rpc("mark_customer_notification_read", { target_notification_id: id }); await load(); }
  async function readAll() { await supabase.rpc("mark_all_customer_notifications_read"); await load(); }
  return <section className="mt-4 overflow-hidden rounded-[1.35rem] border border-slate-200/70 bg-white shadow-sm"><button type="button" onClick={() => setOpen((value) => !value)} className="flex w-full items-center justify-between gap-3 p-4 text-left"><div><p className="text-[0.6rem] font-black uppercase tracking-[0.15em] text-blue-600">Customer notifications</p><h2 className="mt-0.5 text-lg font-black text-[#071a33]">Updates & Alerts</h2><p className="text-xs text-slate-500">Official shipment updates from Balo Logistics.</p></div><div className="flex items-center gap-2">{unread > 0 && <span className="rounded-full bg-yellow-300 px-2.5 py-1 text-xs font-black text-[#071a33]">{unread} unread</span>}<span aria-hidden="true" className="text-lg text-slate-400">{open ? "−" : "+"}</span></div></button>{open && <div className="border-t border-slate-100 p-4"><div className="flex items-center justify-between gap-2"><div className="flex gap-1.5 overflow-x-auto pb-1">{FILTERS.map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-lg px-2.5 py-1.5 text-[0.65rem] font-bold ${filter === item ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{item}</button>)}</div>{unread > 0 && <button onClick={() => void readAll()} className="shrink-0 text-[0.65rem] font-black text-blue-700">Mark all read</button>}</div><div className="mt-3 max-h-[30rem] overflow-y-auto">{loading ? <p className="py-8 text-center text-xs text-slate-500">Loading notifications…</p> : !filtered.length ? <p className="py-8 text-center text-xs text-slate-500">No notifications in this view.</p> : <ol className="grid gap-2">{filtered.map((row) => <li key={row.id}><button onClick={() => void read(row.id)} className={`w-full rounded-xl border p-3 text-left transition hover:shadow-sm ${categoryTone(row.category)} ${row.read_at ? "opacity-70" : "ring-2 ring-blue-100"}`}><div className="flex items-start justify-between gap-2"><div><p className="text-[0.62rem] font-black uppercase tracking-wider">{row.notification_type}</p><p className="mt-1 text-sm font-black">{row.subject}</p></div>{!row.read_at && <span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-blue-600"/>}</div><p className="mt-1 whitespace-pre-line text-xs leading-5 opacity-80">{row.message}</p><time className="mt-2 block text-[0.62rem] font-semibold opacity-60">{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(row.created_at))}</time></button></li>)}</ol>}</div></div>}</section>;
}
