create table if not exists public.shipment_communications (
  id bigint generated by default as identity primary key,
  shipment_id bigint not null references public.shipments(id) on delete cascade,
  title text not null check (length(trim(title)) > 0),
  message text not null check (length(trim(message)) > 0),
  type text not null check (type in ('Information', 'Delay', 'Customs', 'Payment', 'Arrival', 'Delivery', 'Warning', 'Success')),
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  visible_to_customer boolean not null default true,
  viewed_at timestamptz
);

create index if not exists shipment_communications_shipment_created_idx
  on public.shipment_communications (shipment_id, created_at desc, id desc);
create index if not exists shipment_communications_visible_idx
  on public.shipment_communications (shipment_id, visible_to_customer, created_at desc);

alter table public.shipment_communications enable row level security;

drop policy if exists "Authenticated admins can read shipment communications" on public.shipment_communications;
create policy "Authenticated admins can read shipment communications"
  on public.shipment_communications for select to authenticated using (true);
drop policy if exists "Authenticated admins can create shipment communications" on public.shipment_communications;
create policy "Authenticated admins can create shipment communications"
  on public.shipment_communications for insert to authenticated with check (created_by = auth.uid());
drop policy if exists "Authenticated admins can update shipment communications" on public.shipment_communications;
create policy "Authenticated admins can update shipment communications"
  on public.shipment_communications for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated admins can delete shipment communications" on public.shipment_communications;
create policy "Authenticated admins can delete shipment communications"
  on public.shipment_communications for delete to authenticated using (true);

revoke all on public.shipment_communications from anon;
grant select, insert, update, delete on public.shipment_communications to authenticated;
grant usage, select on sequence public.shipment_communications_id_seq to authenticated;

create or replace function public.get_public_shipment_communications(target_tracking_number text)
returns table (id bigint, shipment_id bigint, title text, message text, type text, created_at timestamptz, visible_to_customer boolean)
language sql stable security definer set search_path = public
as $$
  select c.id, c.shipment_id, c.title, c.message, c.type, c.created_at, c.visible_to_customer
  from public.shipment_communications c
  join public.shipments s on s.id = c.shipment_id
  where s.tracking_number = trim(target_tracking_number) and c.visible_to_customer = true
  order by c.created_at desc, c.id desc;
$$;

create or replace function public.mark_shipment_communications_viewed(target_tracking_number text)
returns integer
language plpgsql security definer set search_path = public
as $$
declare affected integer;
begin
  update public.shipment_communications c
  set viewed_at = coalesce(c.viewed_at, now())
  from public.shipments s
  where s.id = c.shipment_id
    and s.tracking_number = trim(target_tracking_number)
    and c.visible_to_customer = true
    and c.viewed_at is null;
  get diagnostics affected = row_count;
  return affected;
end;
$$;

revoke all on function public.get_public_shipment_communications(text) from public;
revoke all on function public.mark_shipment_communications_viewed(text) from public;
grant execute on function public.get_public_shipment_communications(text) to anon, authenticated;
grant execute on function public.mark_shipment_communications_viewed(text) to anon, authenticated;
