create table if not exists public.shipment_events (
  id bigint generated by default as identity primary key,
  shipment_id bigint not null references public.shipments(id) on delete cascade,
  title text not null check (length(trim(title)) > 0),
  description text,
  country text not null check (length(trim(country)) > 0),
  city text not null check (length(trim(city)) > 0),
  event_type text not null check (event_type in (
    'Shipment Created',
    'Shipment Collected',
    'Warehouse Arrival',
    'Warehouse Departure',
    'Customs Clearance',
    'Flight Departure',
    'Flight Arrival',
    'Sea Departure',
    'Sea Arrival',
    'Local Distribution',
    'Out For Delivery',
    'Delivered',
    'Delayed',
    'Exception',
    'Returned'
  )),
  event_time timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists shipment_events_shipment_time_idx
  on public.shipment_events (shipment_id, event_time desc, id desc);

alter table public.shipment_events enable row level security;

drop policy if exists "Public can read shipment events" on public.shipment_events;
create policy "Public can read shipment events"
  on public.shipment_events for select
  using (true);

drop policy if exists "Authenticated admins can create shipment events" on public.shipment_events;
create policy "Authenticated admins can create shipment events"
  on public.shipment_events for insert to authenticated
  with check (true);

drop policy if exists "Authenticated admins can update shipment events" on public.shipment_events;
create policy "Authenticated admins can update shipment events"
  on public.shipment_events for update to authenticated
  using (true) with check (true);

drop policy if exists "Authenticated admins can delete shipment events" on public.shipment_events;
create policy "Authenticated admins can delete shipment events"
  on public.shipment_events for delete to authenticated
  using (true);

grant select on public.shipment_events to anon, authenticated;
grant insert, update, delete on public.shipment_events to authenticated;
grant usage, select on sequence public.shipment_events_id_seq to authenticated;
