-- Store administrator-only notes separately from customer-facing shipment history.
-- Existing shipment_history rows and customer-visible notes remain unchanged.

create unique index if not exists shipment_history_id_shipment_id_uidx
  on public.shipment_history (id, shipment_id);

create table if not exists public.shipment_history_internal_notes (
  id bigint generated by default as identity primary key,
  shipment_id bigint not null references public.shipments(id) on delete cascade,
  shipment_history_id bigint not null unique,
  note text not null check (pg_catalog.length(pg_catalog.btrim(note)) > 0),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shipment_history_internal_notes_history_shipment_fkey
    foreign key (shipment_history_id, shipment_id)
    references public.shipment_history(id, shipment_id)
    on delete cascade
);

create index if not exists shipment_history_internal_notes_shipment_created_idx
  on public.shipment_history_internal_notes (shipment_id, created_at desc, id desc);

alter table public.shipment_history_internal_notes enable row level security;

drop policy if exists "Administrators can read shipment history internal notes"
  on public.shipment_history_internal_notes;
drop policy if exists "Administrators can create shipment history internal notes"
  on public.shipment_history_internal_notes;
drop policy if exists "Administrators can update shipment history internal notes"
  on public.shipment_history_internal_notes;
drop policy if exists "Administrators can delete shipment history internal notes"
  on public.shipment_history_internal_notes;

create policy "Administrators can read shipment history internal notes"
  on public.shipment_history_internal_notes for select to authenticated
  using ((select public.is_admin()));

create policy "Administrators can create shipment history internal notes"
  on public.shipment_history_internal_notes for insert to authenticated
  with check ((select public.is_admin()));

create policy "Administrators can update shipment history internal notes"
  on public.shipment_history_internal_notes for update to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

create policy "Administrators can delete shipment history internal notes"
  on public.shipment_history_internal_notes for delete to authenticated
  using ((select public.is_admin()));

revoke all on table public.shipment_history_internal_notes from public, anon, authenticated;
grant select, insert, update, delete on table public.shipment_history_internal_notes to authenticated;

revoke all on sequence public.shipment_history_internal_notes_id_seq from public, anon, authenticated;
grant usage, select on sequence public.shipment_history_internal_notes_id_seq to authenticated;
