create table if not exists public.shipment_documents (
  id bigint generated by default as identity primary key,
  shipment_id bigint not null references public.shipments(id) on delete cascade,
  document_name text not null check (length(trim(document_name)) > 0),
  document_type text not null check (document_type in (
    'Commercial Invoice',
    'Packing List',
    'Air Waybill',
    'Bill of Lading',
    'Customs Declaration',
    'Delivery Note',
    'Insurance Certificate',
    'Import Permit',
    'Export Permit',
    'Proof of Delivery',
    'Other'
  )),
  file_url text not null check (length(trim(file_url)) > 0),
  file_size bigint not null check (file_size >= 0),
  uploaded_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null
);

create index if not exists shipment_documents_shipment_uploaded_idx
  on public.shipment_documents (shipment_id, uploaded_at desc, id desc);

alter table public.shipment_documents enable row level security;

drop policy if exists "Public can read shipment documents" on public.shipment_documents;
create policy "Public can read shipment documents"
  on public.shipment_documents for select
  using (true);

drop policy if exists "Authenticated admins can create shipment documents" on public.shipment_documents;
create policy "Authenticated admins can create shipment documents"
  on public.shipment_documents for insert to authenticated
  with check (created_by = auth.uid());

drop policy if exists "Authenticated admins can update shipment documents" on public.shipment_documents;
create policy "Authenticated admins can update shipment documents"
  on public.shipment_documents for update to authenticated
  using (true) with check (true);

drop policy if exists "Authenticated admins can delete shipment documents" on public.shipment_documents;
create policy "Authenticated admins can delete shipment documents"
  on public.shipment_documents for delete to authenticated
  using (true);

grant select on public.shipment_documents to anon, authenticated;
grant insert, update, delete on public.shipment_documents to authenticated;
grant usage, select on sequence public.shipment_documents_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit)
values ('shipment-documents', 'shipment-documents', true, 26214400)
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit;

drop policy if exists "Public can read shipment document files" on storage.objects;
create policy "Public can read shipment document files"
  on storage.objects for select
  using (bucket_id = 'shipment-documents');

drop policy if exists "Authenticated admins can upload shipment document files" on storage.objects;
create policy "Authenticated admins can upload shipment document files"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'shipment-documents');

drop policy if exists "Authenticated admins can update shipment document files" on storage.objects;
create policy "Authenticated admins can update shipment document files"
  on storage.objects for update to authenticated
  using (bucket_id = 'shipment-documents')
  with check (bucket_id = 'shipment-documents');

drop policy if exists "Authenticated admins can delete shipment document files" on storage.objects;
create policy "Authenticated admins can delete shipment document files"
  on storage.objects for delete to authenticated
  using (bucket_id = 'shipment-documents');
